#!/usr/bin/env python

import rackspace.exp.rest.base.util
import rackspace.exp.objs.lbaas
import clientUtils
import json
import sys
import os

util = rackspace.exp.rest.base.util.BaseUtil
printf = util.printf
lbaas = rackspace.exp.objs.lbaas.lbaas
clientUtils.lbaas.headers = clientUtils.xmlHdrs



resp = clientUtils.lbaas.getLoadBalancers()
xml = resp.read()
lbs = lbaas.CreateFromDocument(xml)

if util.pyXBName(lbs) != "loadBalancers":
    sys.stdout.write("Error object returned was %s\n"%pyXBName(lbs))
    sys.exit()

for lb in lbs.loadBalancer:
    cols = ["name","id","port","protocol","status"]
    msg = "lb %s:\n"%(clientUtils.attrStrs(lb,*cols))
    sys.stdout.write(msg)
    sys.stdout.write("vips\n")
    for vip in lb.virtualIps.virtualIp:
        msg = "   vip %s:\n"%(clientUtils.attrStrs(vip,"id","type","address"))
        sys.stdout.write(msg)
    sys.stdout.write("\n\n")

