#!/usr/bin/env python

import sys
import os

sys.path.insert(0,os.path.split(os.path.abspath(os.path.dirname(__file__)))[0])
import rackspace.exp.rest.base.util
import rackspace.exp.objs.lbaas
import clientUtils

util = rackspace.exp.rest.base.util.BaseUtil
printf = util.printf
lbaas = rackspace.exp.objs.lbaas.lbaas
clientUtils.lbaas.headers = clientUtils.xmlHdrs

def usage(prog):
    printf("Usage is %s <lb_id>\n",prog)
    printf("\n")

prog = os.path.basename(sys.argv[0])
if len(sys.argv)<2:
    usage(prog)
    sys.exit()

lid = int(sys.argv[1])
resp = clientUtils.lbaas.delLoadBalancer(lid)

