#!/usr/bin/env python

import rackspace.exp.rest.base.util
import json
import sys
import os

util = rackspace.exp.rest.base.util.BaseUtil

def usage(prog):
    util.printf("usage is %s <accountId>\n",prog)
    util.printf("\n")
    util.printf("Sets the current account id for api calls\n")
    util.printf("\n")
    util.printf("Good Choices are:\n")

prog = os.path.basename(sys.argv[0])
if len(sys.argv)<2:
    usage(prog)
    sys.exit()

endpoint = sys.argv[1]

try:
    conf = util.load_json("conf.json")
except:
    conf = {}

conf["account"] = int(sys.argv[1])
util.save_json("conf.json",conf)

