#!/usr/bin/env python

import sys
import os

sys.path.insert(0,os.path.split(os.path.abspath(os.path.dirname(__file__)))[0])
import rackspace.exp.rest.base.util
import rackspace.exp.objs.dns
import clientUtils

util = rackspace.exp.rest.base.util.BaseUtil
printf = util.printf
dns = rackspace.exp.objs.dns.dns

resp = clientUtils.dns.getDomains()
xml = resp.read()

domains = dns.CreateFromDocument(xml)

for d in domains.domain:
    cols = ["id","accountId","name","ttl","emailAddress","status","created",
            "owner","contentType","comment"]
    msg = "domain %s:\n"%(clientUtils.attrStrs(d,*cols))
    sys.stdout.write(msg)
