#!/usr/bin/env python

import rackspace.exp.rest.base.util
import clientUtils
import sys
import os

util = rackspace.exp.rest.base.util.BaseUtil
printf = util.printf

dns = clientUtils.dns

resp = dns.getDomains()
obj = resp.read()
