#!/usr/bin/env python

import sys
import os

sys.path.insert(0,os.path.split(os.path.abspath(os.path.dirname(__file__)))[0])
import rackspace.exp.rest.base.util
import rackspace.exp.objs.dns
import clientUtils

util = rackspace.exp.rest.base.util.BaseUtil
printf = util.printf

def usage(prog):
    printf("usage is %s <domainId>\n",prog)
    printf("\n")
    printf("Fetch records for this domain\n")

dns = rackspace.exp.objs.dns.dns

prog = os.path.basename(sys.argv[0])
if len(sys.argv)<2:
    usage(prog)
    sys.exit()

domain_id = int(sys.argv[1])
account_id = clientUtils.dns.account
printf("Records for account=%i domain=%i\n",account_id,domain_id)
printf("="*75)
printf("\n")

resp = clientUtils.dns.getRecords(domain_id)
xml = resp.read()
records = dns.CreateFromDocument(xml)

for r in records.record:
    cols = ["name","id","type","data","ttl","priority","status","updated",
            "created","comment"]
    msg = "record %s\n%s\n"%(r.name,clientUtils.attrStrs(r,*cols))
    sys.stdout.write(msg)

